sudo: false

language: php

env:
  global:
    - SYMFONY_VERSION=""
    - deps=""

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.3
      env: deps="low"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x@dev"
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi

install:
  - if [ "$deps" = "" ]; then composer install; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
